---
development:
  cloud_name: ddr73hpdw
  api_key: '145125595377555'
  api_secret: UHk5WCYpULsMb6cD1uvJmZDqbks
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ddr73hpdw
  api_key: '145125595377555'
  api_secret: UHk5WCYpULsMb6cD1uvJmZDqbks
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ddr73hpdw
  api_key: '145125595377555'
  api_secret: UHk5WCYpULsMb6cD1uvJmZDqbks
  enhance_image_tag: true
  static_image_support: false
