name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:9.6.15
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: 'postgres'
          POSTGRES_DB: pubmap_test
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 1s
          --health-retries 10
        ports: ['5432:5432']

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/pubmap_test
      RAILS_ENV: test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6

    - name: Ruby gem cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Set up database
      run: bundle exec rake db:setup

    - name: Code Climate before-build
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Run tests
      run: bundle exec rspec

    - name: Code Climate upload results
      run: |
        ./cc-test-reporter after-build -r $CC_TEST_REPORTER_ID

