name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: pabloscolpino/publication-mapper

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: ${{ github.actor }}
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.GITHUB_TOKEN }}
          # Docker repository to tag the image with
          repository: pabloscolpino/publication-mapper
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: latest
          # Automatically tags the built image with the git reference as per the readme
          # tag_with_ref: # optional
          # Automatically tags the built image with the git short SHA as per the readme
          # tag_with_sha: # optional
          #
          # Path to the build context
          # Sets the target stage to build
          target: production
          # Always attempt to pull a newer version of the image
          # always_pull: # optional
          # Comma-delimited list of build-time variables
          # build_args: # optional
          # Comma-delimited list of images to consider as cache sources
          # cache_froms: # optional
          # Comma-delimited list of labels to add to the built image
          # labels: # optional
          # Adds labels with git repository information to the built image
          # add_git_labels: # optional
          # Whether to push the image
          # push: # optional, default is true
